keys:
  - &primary age1wa5q2njpt233mtztksnn5lwtkmtf3cdaem3rjxenzy9dfhvjj5ssjpvr4h
  - &ssh_ken 564A6B11CD96E3C24BD4FDB4A09E0B814F529F78
creation_rules:
  - path_regex: config/secrets.yaml$  #secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *ssh_ken
    - age:
      - *primary
