hello: ENC[AES256_GCM,data:4JUvtp84qTUpbZtFYAlOIKoyPUb1kqD2rxoZ4On10phwLQNR6J9qlFRXfClTTw==,iv:9ti61Go+VErerrJMuw/KorV3nfONq+Z4Y+0sMrfkeqc=,tag:6ALPNz6i2/xgffmzmy6TEw==,type:str]
example_key: ENC[AES256_GCM,data:C0JSfTfLnEiUa3aH2A==,iv:cZ9JRiteN9rRrJYl2TgLEFXAgUyATVhGPLjzDfeRIBE=,tag:zS6zYF2uamIAmLwHaUDWBA==,type:str]
#ENC[AES256_GCM,data:bPClHhtRyeYcjoVIoSLUHg==,iv:zY+9Vt94i/dHBlnQIBrlcgHASEV6e8gqOOBf1SjJ2OU=,tag:+ZbyPfwHZ9fxAs9q0IChlg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:rKl1Ppz1Bgy+GWNgLe8=,iv:BsQ5UJlPmCQYaoQkaMomJXrfHetmSZa++arcav75jws=,tag:GDGtlo6at1sDyAHE0hVDfQ==,type:str]
    - ENC[AES256_GCM,data:6BLgCVgwEN7JcH1JHcY=,iv:oKE/rIaBp+ZRgxpdhjzePsxD6IR3rNPx6djN+YGd8qs=,tag:PioZ+lEFebXMCOIWj4rKwA==,type:str]
example_number: ENC[AES256_GCM,data:hPLOeLIdVOUS9w==,iv:tFwhO2LGOnpyU/12kcTKpfPb76l/mBSq2Slkwi7DQps=,tag:3x9O5u1N67YSdLdkZ2tMDQ==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:x/c/cQ==,iv:7H9SKS/qB3kLviQd1i7XxNyYddEZ85g16GHwC3Mz5K4=,tag:S3B0vThyw2/L3J/YVbGutQ==,type:bool]
    - ENC[AES256_GCM,data:HZ5yTbo=,iv:sL8QhvhvQNku0HLS3ZGa5AItaUd3EgPn/iqi16upnFQ=,tag:+9QPEbofx30ZD/eCs8MWCA==,type:bool]
myservice:
    my_subdir:
        my_secret: ENC[AES256_GCM,data:wm5NjkmqmusR,iv:geWsLlrsuBjav9Pauknv9Cu4IBO6CD0gpElmXX4NfAQ=,tag:Q0N8yVmdLmhUnGxpNcxNdQ==,type:str]
sops:
    shamir_threshold: 2
    key_groups:
        - pgp:
            - created_at: "2025-03-27T13:17:12Z"
              enc: |-
                -----BEGIN PGP MESSAGE-----

                hF4DbpwHitFgEg8SAQdAFquaE7c89C7EwCh/o58mBeTQjIgPbufC8nqvInBCBBcw
                5IF7D8fnw2nd1rf2Pk/VZX3LEWmYi2iKCuL0HZpscXAR3F5+9XhURC6Fo/EWr+Xz
                0l8BJNJwgEjl3V1BQMnXZsWU3x12Cij7AmtdTWlVeLZOW/4U/zpRup0yfvLcJak3
                UPldqKJKiWpnsKYfCdfwsnwmi+p18Cb9hDFf3tt+ot5j0hS0ULRYqYaOfUr5/bAy
                Qg==
                =Jl5+
                -----END PGP MESSAGE-----
              fp: 564A6B11CD96E3C24BD4FDB4A09E0B814F529F78
          hc_vault: []
          age: []
        - hc_vault: []
          age:
            - recipient: age1wa5q2njpt233mtztksnn5lwtkmtf3cdaem3rjxenzy9dfhvjj5ssjpvr4h
              enc: |
                -----BEGIN AGE ENCRYPTED FILE-----
                YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMm1ySXg0OENmdXY2dGxE
                RWUrK3JZb3ZDaXNMWUdmZFRMdS80SEYycmdJCmFWODcvanJIWHIvL0hpTWxibWFC
                S21uMTcvdFZsN2lpN3ZWWFRIUVZkVlUKLS0tIDRRMDJEV0hFbnJaOUVGdS93RnBY
                Mi90d1BOUXVGaC9MOUxLVTFwUzBNdVEKIgiOXAU8U29nsfvKYsWwMUrUF++3Zpgu
                akX1FwwevfJV889f6DnSokKHqwoUaaxNUPs1oE09cmJ7qwJPn2FS8pE=
                -----END AGE ENCRYPTED FILE-----
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-27T13:17:57Z"
    mac: ENC[AES256_GCM,data:0gru6LBwFajwDDKcHM5VCevueLlxgHVtpmEDKtPLNyPvW6pQ+bzNuy2Ig7tHdpX8X837ecKza2Sbd1wrw31q1bFEMR4FcdG6jdstwn3pKLOyhK6ztqkh33/4efySwdY8xlQmQp0/dP+Wg+9agwAiq33xR+A0MVNVybWOxSJ5GG0=,iv:PZnVJHFiCpTXahw2h/1i6KmLf/+Fn7vt+VDouLgdLNg=,tag:EDpIPyYYE5dN8ZQ7+xfhTQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
